[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Amazon Experience Area 2024"
authors = [{name = "Editor", email = "editor@here"}]
dynamic = ["version", "description"]
